### ISSUE TITLE
Failure to build on Ubuntu 18.04 Linux - SRT

### ISSUE THREAD

**Issue by WizzerWorks** [jjustman/libatsc3#125]
I see the following error while attempting to build using

````
src/build_linux.sh
`````
g++ -Wno-nullability-completeness -Wno-expansion-to-defined -Wno-builtin-requires-header -Wno-c++11-extensions  -Wno-writable-strings -I ../android/atsc3_core/libpcre/include -I ../openssl/build_ssl/include -std=c++11 -Wno-writable-strings -g \
	-c phy/virtual/PcapSTLTPVirtualPHY.cpp \
	-o PcapSTLTPVirtualPHY.o  -I.
g++ -Wno-nullability-completeness -Wno-expansion-to-defined -Wno-builtin-requires-header -Wno-c++11-extensions  -Wno-writable-strings -I ../android/atsc3_core/libpcre/include -I ../openssl/build_ssl/include -std=c++11 -Wno-writable-strings -g \
	-DHAI_ENABLE_SRT=1 -DHAI_PATCH=1 -DHAVE_INET_PTON=1 -DOSX=1 -DSRT_ENABLE_APP_READER -DSRT_ENABLE_CLOSE_SYNCH -DSRT_ENABLE_ENCRYPTION -DSRT_ENABLE_VERBOSE_LOCK -DSRT_VERSION=\"1.4.1\" -DUSE_OPENSSL=1 -D_GNU_SOURCE \
 	-I. -I phy/virtual/srt -I ../srt -I ../srt/build/include \
	-c phy/virtual/srt/atsc3_srt_live_receiver.cpp \
	-o atsc3_srt_live_receiver.o
In file included from phy/virtual/srt/atsc3_srt_live_receiver.cpp:77:0:
phy/virtual/srt/apputil.hpp:66:10: fatal error: srtcore/srt.h: No such file or directory
 #include <srtcore/srt.h> // Required for stats module
          ^~~~~~~~~~~~~~~
compilation terminated.

**Comment by useffc** [comment]
@WizzerWorks I was running into this issue and the one you describe in #124 as well. It seems several of the git submodules are on private SBGTV repos, and despite the assurance that a user can bypass the user/password prompts, not all of the submodules' contents get pulled down.

Here's what worked for me: For any submodule folder whose contents are empty, such as `/srt`, `cd` into that directory and `git clone` the repo that's needed. Be sure to `git checkout` the specific tree hash referred to in the submodule.

**Comment by jjustman** [comment]
For the SRT folder, the submodule ref doesn't seem to be pointing to the proper commit, please try:

cd srt
git reset --hard
